cache:
  directories:
    – $HOME/.m2
    – $HOME/.sonar/cache

jdk: oraclejdk8
language: java
script: mvn clean install sonar:sonar -Dsonar.organization=tusharvjoshi-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
