    cache:
    directories:
    – $HOME/.m2
    – $HOME/.sonar/cache

    env:
    jdk: oraclejdk8
    language: java
    script: mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
